# -*- coding: utf-8 -*-
import numpy as np
import copy
from typing import Optional, List
import torch
import torch.nn.functional as F
from torch import nn, Tensor

import warnings
from typing import Tuple, Optional

import torch
from torch import Tensor
from torch.nn.modules.linear import Linear
from torch.nn.init import xavier_uniform_
from torch.nn.init import constant_
from torch.nn.init import xavier_normal_
from torch.nn.parameter import Parameter
from torch.nn.modules.module import Module
from torch.nn import functional as F
from ss_moe.ss_moe import SS_MoE
import warnings
import math

from torch._C import _infer_size, _add_docstr
from torch.nn import _reduction as _Reduction
from torch.nn.modules import utils
from torch.nn.modules.utils import _single, _pair, _triple, _list_with_default
from torch.nn import grad
from torch import _VF
from torch._jit_internal import boolean_dispatch, List, Optional, _overload, Tuple
try:
    from torch.overrides import has_torch_function, handle_torch_function
except:
    from torch._overrides import has_torch_function, handle_torch_function
Tensor = torch.Tensor

from torch.nn.functional import linear, pad, softmax, dropout

from conformer2 import Conformer

class MultiheadAttention(Module):
    r"""Allows the model to jointly attend to information
    from different representation subspaces.
    See reference: Attention Is All You Need
    .. math::
        \text{MultiHead}(Q, K, V) = \text{Concat}(head_1,\dots,head_h)W^O
        \text{where} head_i = \text{Attention}(QW_i^Q, KW_i^K, VW_i^V)
    Args:
        embed_dim: total dimension of the model.
        num_heads: parallel attention heads.
        dropout: a Dropout layer on attn_output_weights. Default: 0.0.
        bias: add bias as module parameter. Default: True.
        add_bias_kv: add bias to the key and value sequences at dim=0.
        add_zero_attn: add a new batch of zeros to the key and
                       value sequences at dim=1.
        kdim: total number of features in key. Default: None.
        vdim: total number of features in value. Default: None.
        Note: if kdim and vdim are None, they will be set to embed_dim such that
        query, key, and value have the same number of features.
    Examples::
        >>> multihead_attn = nn.MultiheadAttention(embed_dim, num_heads)
        >>> attn_output, attn_output_weights = multihead_attn(query, key, value)
    """
    bias_k: Optional[torch.Tensor]
    bias_v: Optional[torch.Tensor]

    def __init__(self, embed_dim, num_heads, dropout=0., bias=True, add_bias_kv=False, add_zero_attn=False, kdim=None, vdim=None):
        super(MultiheadAttention, self).__init__()
        self.embed_dim = embed_dim
        self.kdim = kdim if kdim is not None else embed_dim
        self.vdim = vdim if vdim is not None else embed_dim
        self._qkv_same_embed_dim = self.kdim == embed_dim and self.vdim == embed_dim

        self.num_heads = num_heads
        self.dropout = dropout
        self.head_dim = embed_dim // num_heads
        assert self.head_dim * num_heads == self.embed_dim, "embed_dim must be divisible by num_heads"

        vdim = vdim if vdim is not None else embed_dim
        self.out_proj = Linear(vdim , vdim)

        self.in_proj_bias = None
        self.in_proj_weight = None
        self.bias_k = self.bias_v = None
        self.q_proj_weight = None
        self.k_proj_weight = None
        self.v_proj_weight = None

        self.add_zero_attn = add_zero_attn

        self._reset_parameters()

    def _reset_parameters(self):
        constant_(self.out_proj.bias, 0.)

    def __setstate__(self, state):
        # Support loading old MultiheadAttention checkpoints generated by v1.1.0
        if '_qkv_same_embed_dim' not in state:
            state['_qkv_same_embed_dim'] = True

        super(MultiheadAttention, self).__setstate__(state)

    def forward(self, query, key, value, key_padding_mask=None,
                need_weights=True, attn_mask=None):
        # type: (Tensor, Tensor, Tensor, Optional[Tensor], bool, Optional[Tensor]) -> Tuple[Tensor, Optional[Tensor]]
        r"""
    Args:
        query, key, value: map a query and a set of key-value pairs to an output.
            See "Attention Is All You Need" for more details.
        key_padding_mask: if provided, specified padding elements in the key will
            be ignored by the attention. When given a binary mask and a value is True,
            the corresponding value on the attention layer will be ignored. When given
            a byte mask and a value is non-zero, the corresponding value on the attention
            layer will be ignored
        need_weights: output attn_output_weights.
        attn_mask: 2D or 3D mask that prevents attention to certain positions. A 2D mask will be broadcasted for all
            the batches while a 3D mask allows to specify a different mask for the entries of each batch.
    Shape:
        - Inputs:
        - query: :math:`(L, N, E)` where L is the target sequence length, N is the batch size, E is
          the embedding dimension.
        - key: :math:`(S, N, E)`, where S is the source sequence length, N is the batch size, E is
          the embedding dimension.
        - value: :math:`(S, N, E)` where S is the source sequence length, N is the batch size, E is
          the embedding dimension.
        - key_padding_mask: :math:`(N, S)` where N is the batch size, S is the source sequence length.
          If a ByteTensor is provided, the non-zero positions will be ignored while the position
          with the zero positions will be unchanged. If a BoolTensor is provided, the positions with the
          value of ``True`` will be ignored while the position with the value of ``False`` will be unchanged.
        - attn_mask: 2D mask :math:`(L, S)` where L is the target sequence length, S is the source sequence length.
          3D mask :math:`(N*\text{num_heads}, L, S)` where N is the batch size, L is the target sequence length,
          S is the source sequence length. attn_mask ensure that position i is allowed to attend the unmasked
          positions. If a ByteTensor is provided, the non-zero positions are not allowed to attend
          while the zero positions will be unchanged. If a BoolTensor is provided, positions with ``True``
          is not allowed to attend while ``False`` values will be unchanged. If a FloatTensor
          is provided, it will be added to the attention weight.
        - Outputs:
        - attn_output: :math:`(L, N, E)` where L is the target sequence length, N is the batch size,
          E is the embedding dimension.
        - attn_output_weights: :math:`(N, L, S)` where N is the batch size,
          L is the target sequence length, S is the source sequence length.
        """
        if not self._qkv_same_embed_dim:
            return multi_head_attention_forward(
                query, key, value, self.embed_dim, self.num_heads,
                self.in_proj_weight, self.in_proj_bias,
                self.bias_k, self.bias_v, self.add_zero_attn,
                self.dropout, self.out_proj.weight, self.out_proj.bias,
                training=self.training,
                key_padding_mask=key_padding_mask, need_weights=need_weights,
                attn_mask=attn_mask, use_separate_proj_weight=True,
                q_proj_weight=self.q_proj_weight, k_proj_weight=self.k_proj_weight,
                v_proj_weight=self.v_proj_weight, out_dim=self.vdim)
        else:
            return multi_head_attention_forward(
                query, key, value, self.embed_dim, self.num_heads,
                self.in_proj_weight, self.in_proj_bias,
                self.bias_k, self.bias_v, self.add_zero_attn,
                self.dropout, self.out_proj.weight, self.out_proj.bias,
                training=self.training,
                key_padding_mask=key_padding_mask, need_weights=need_weights,
                attn_mask=attn_mask, out_dim=self.vdim)


def multi_head_attention_forward(query: Tensor,
                                 key: Tensor,
                                 value: Tensor,
                                 embed_dim_to_check: int,
                                 num_heads: int,
                                 in_proj_weight: Tensor,
                                 in_proj_bias: Tensor,
                                 bias_k: Optional[Tensor],
                                 bias_v: Optional[Tensor],
                                 add_zero_attn: bool,
                                 dropout_p: float,
                                 out_proj_weight: Tensor,
                                 out_proj_bias: Tensor,
                                 training: bool = True,
                                 key_padding_mask: Optional[Tensor] = None,
                                 need_weights: bool = True,
                                 attn_mask: Optional[Tensor] = None,
                                 use_separate_proj_weight: bool = False,
                                 q_proj_weight: Optional[Tensor] = None,
                                 k_proj_weight: Optional[Tensor] = None,
                                 v_proj_weight: Optional[Tensor] = None,
                                 static_k: Optional[Tensor] = None,
                                 static_v: Optional[Tensor] = None,
                                 out_dim: Optional[Tensor] = None
                                 ) -> Tuple[Tensor, Optional[Tensor]]:
    r"""
    Args:
        query, key, value: map a query and a set of key-value pairs to an output.
            See "Attention Is All You Need" for more details.
        embed_dim_to_check: total dimension of the model.
        num_heads: parallel attention heads.
        in_proj_weight, in_proj_bias: input projection weight and bias.
        bias_k, bias_v: bias of the key and value sequences to be added at dim=0.
        add_zero_attn: add a new batch of zeros to the key and
                       value sequences at dim=1.
        dropout_p: probability of an element to be zeroed.
        out_proj_weight, out_proj_bias: the output projection weight and bias.
        training: apply dropout if is ``True``.
        key_padding_mask: if provided, specified padding elements in the key will
            be ignored by the attention. This is an binary mask. When the value is True,
            the corresponding value on the attention layer will be filled with -inf.
        need_weights: output attn_output_weights.
        attn_mask: 2D or 3D mask that prevents attention to certain positions. A 2D mask will be broadcasted for all
            the batches while a 3D mask allows to specify a different mask for the entries of each batch.
        use_separate_proj_weight: the function accept the proj. weights for query, key,
            and value in different forms. If false, in_proj_weight will be used, which is
            a combination of q_proj_weight, k_proj_weight, v_proj_weight.
        q_proj_weight, k_proj_weight, v_proj_weight, in_proj_bias: input projection weight and bias.
        static_k, static_v: static key and value used for attention operators.
    Shape:
        Inputs:
        - query: :math:`(L, N, E)` where L is the target sequence length, N is the batch size, E is
          the embedding dimension.
        - key: :math:`(S, N, E)`, where S is the source sequence length, N is the batch size, E is
          the embedding dimension.
        - value: :math:`(S, N, E)` where S is the source sequence length, N is the batch size, E is
          the embedding dimension.
        - key_padding_mask: :math:`(N, S)` where N is the batch size, S is the source sequence length.
          If a ByteTensor is provided, the non-zero positions will be ignored while the zero positions
          will be unchanged. If a BoolTensor is provided, the positions with the
          value of ``True`` will be ignored while the position with the value of ``False`` will be unchanged.
        - attn_mask: 2D mask :math:`(L, S)` where L is the target sequence length, S is the source sequence length.
          3D mask :math:`(N*num_heads, L, S)` where N is the batch size, L is the target sequence length,
          S is the source sequence length. attn_mask ensures that position i is allowed to attend the unmasked
          positions. If a ByteTensor is provided, the non-zero positions are not allowed to attend
          while the zero positions will be unchanged. If a BoolTensor is provided, positions with ``True``
          are not allowed to attend while ``False`` values will be unchanged. If a FloatTensor
          is provided, it will be added to the attention weight.
        - static_k: :math:`(N*num_heads, S, E/num_heads)`, where S is the source sequence length,
          N is the batch size, E is the embedding dimension. E/num_heads is the head dimension.
        - static_v: :math:`(N*num_heads, S, E/num_heads)`, where S is the source sequence length,
          N is the batch size, E is the embedding dimension. E/num_heads is the head dimension.
        Outputs:
        - attn_output: :math:`(L, N, E)` where L is the target sequence length, N is the batch size,
          E is the embedding dimension.
        - attn_output_weights: :math:`(N, L, S)` where N is the batch size,
          L is the target sequence length, S is the source sequence length.
    """
    if not torch.jit.is_scripting():
        tens_ops = (query, key, value, in_proj_weight, in_proj_bias, bias_k, bias_v,
                    out_proj_weight, out_proj_bias)
        if any([type(t) is not Tensor for t in tens_ops]) and has_torch_function(tens_ops):
            return handle_torch_function(
                multi_head_attention_forward, tens_ops, query, key, value,
                embed_dim_to_check, num_heads, in_proj_weight, in_proj_bias,
                bias_k, bias_v, add_zero_attn, dropout_p, out_proj_weight,
                out_proj_bias, training=training, key_padding_mask=key_padding_mask,
                need_weights=need_weights, attn_mask=attn_mask,
                use_separate_proj_weight=use_separate_proj_weight,
                q_proj_weight=q_proj_weight, k_proj_weight=k_proj_weight,
                v_proj_weight=v_proj_weight, static_k=static_k, static_v=static_v)
    tgt_len, bsz, embed_dim = query.size()
    assert embed_dim == embed_dim_to_check
    # allow MHA to have different sizes for the feature dimension
    assert key.size(0) == value.size(0) and key.size(1) == value.size(1)

    head_dim = embed_dim // num_heads
    v_head_dim = out_dim // num_heads
    assert head_dim * num_heads == embed_dim, "embed_dim must be divisible by num_heads"
    scaling = float(head_dim) ** -0.5

    q = query * scaling
    k = key
    v = value

    if attn_mask is not None:
        assert attn_mask.dtype == torch.float32 or attn_mask.dtype == torch.float64 or \
            attn_mask.dtype == torch.float16 or attn_mask.dtype == torch.uint8 or attn_mask.dtype == torch.bool, \
            'Only float, byte, and bool types are supported for attn_mask, not {}'.format(attn_mask.dtype)
        if attn_mask.dtype == torch.uint8:
            warnings.warn("Byte tensor for attn_mask in nn.MultiheadAttention is deprecated. Use bool tensor instead.")
            attn_mask = attn_mask.to(torch.bool)

        if attn_mask.dim() == 2:
            attn_mask = attn_mask.unsqueeze(0)
            if list(attn_mask.size()) != [1, query.size(0), key.size(0)]:
                raise RuntimeError('The size of the 2D attn_mask is not correct.')
        elif attn_mask.dim() == 3:
            if list(attn_mask.size()) != [bsz * num_heads, query.size(0), key.size(0)]:
                raise RuntimeError('The size of the 3D attn_mask is not correct.')
        else:
            raise RuntimeError("attn_mask's dimension {} is not supported".format(attn_mask.dim()))
        # attn_mask's dim is 3 now.

    # convert ByteTensor key_padding_mask to bool
    if key_padding_mask is not None and key_padding_mask.dtype == torch.uint8:
        warnings.warn("Byte tensor for key_padding_mask in nn.MultiheadAttention is deprecated. Use bool tensor instead.")
        key_padding_mask = key_padding_mask.to(torch.bool)

    if bias_k is not None and bias_v is not None:
        if static_k is None and static_v is None:
            k = torch.cat([k, bias_k.repeat(1, bsz, 1)])
            v = torch.cat([v, bias_v.repeat(1, bsz, 1)])
            if attn_mask is not None:
                attn_mask = pad(attn_mask, (0, 1))
            if key_padding_mask is not None:
                key_padding_mask = pad(key_padding_mask, (0, 1))
        else:
            assert static_k is None, "bias cannot be added to static key."
            assert static_v is None, "bias cannot be added to static value."
    else:
        assert bias_k is None
        assert bias_v is None

    q = q.contiguous().view(tgt_len, bsz * num_heads, head_dim).transpose(0, 1)
    if k is not None:
        k = k.contiguous().view(-1, bsz * num_heads, head_dim).transpose(0, 1)
    if v is not None:
        v = v.contiguous().view(-1, bsz * num_heads, v_head_dim).transpose(0, 1)

    if static_k is not None:
        assert static_k.size(0) == bsz * num_heads
        assert static_k.size(2) == head_dim
        k = static_k

    if static_v is not None:
        assert static_v.size(0) == bsz * num_heads
        assert static_v.size(2) == v_head_dim
        v = static_v

    src_len = k.size(1)

    if key_padding_mask is not None:
        assert key_padding_mask.size(0) == bsz
        assert key_padding_mask.size(1) == src_len

    if add_zero_attn:
        src_len += 1
        k = torch.cat([k, torch.zeros((k.size(0), 1) + k.size()[2:], dtype=k.dtype, device=k.device)], dim=1)
        v = torch.cat([v, torch.zeros((v.size(0), 1) + v.size()[2:], dtype=v.dtype, device=v.device)], dim=1)
        if attn_mask is not None:
            attn_mask = pad(attn_mask, (0, 1))
        if key_padding_mask is not None:
            key_padding_mask = pad(key_padding_mask, (0, 1))

    attn_output_weights = torch.bmm(q, k.transpose(1, 2))
    assert list(attn_output_weights.size()) == [bsz * num_heads, tgt_len, src_len]

    if attn_mask is not None:
        if attn_mask.dtype == torch.bool:
            attn_output_weights.masked_fill_(attn_mask, float('-inf'))
        else:
            attn_output_weights += attn_mask


    if key_padding_mask is not None:
        attn_output_weights = attn_output_weights.view(bsz, num_heads, tgt_len, src_len)
        attn_output_weights = attn_output_weights.masked_fill(
            key_padding_mask.unsqueeze(1).unsqueeze(2),
            float('-inf'),
        )
        attn_output_weights = attn_output_weights.view(bsz * num_heads, tgt_len, src_len)

    # attn_output_weights = softmax(
    #     attn_output_weights, dim=-1)
    attn_output_weights = softmax(
            attn_output_weights - attn_output_weights.max(dim=-1, keepdim=True)[0], dim=-1)
    attn_output_weights = dropout(attn_output_weights, p=dropout_p, training=training)

    attn_output = torch.bmm(attn_output_weights, v)
    assert list(attn_output.size()) == [bsz * num_heads, tgt_len, v_head_dim]
    attn_output = attn_output.transpose(0, 1).contiguous().view(tgt_len, bsz, out_dim)
    attn_output = linear(attn_output, out_proj_weight, out_proj_bias)

    if need_weights:
        # average attention weights over heads
        attn_output_weights = attn_output_weights.view(bsz, num_heads, tgt_len, src_len)
        return attn_output, attn_output_weights.sum(dim=1) / num_heads
    else:
        return attn_output, None


class CNN2D_BN_Relu(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride=1):
        super(CNN2D_BN_Relu, self).__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding=kernel_size//2)
        self.bn = nn.BatchNorm2d(out_channels) #(N,C,H,W) on C
        self.relu = nn.ReLU(True)

    def forward(self, x):
        out = self.conv(x)
        out = self.bn(out)
        out = self.relu(out)
        return out



class MA_MSE(nn.Module):
    def __init__(self, fea_dim=512, n_heads=8, speaker_embedding_path=""):
        super(MA_MSE, self).__init__()

        self.n_heads = n_heads

        #Dictionary number of cluster * speaker_embedding_dim
        self.m = torch.from_numpy(np.load(speaker_embedding_path).astype(np.float32))
        #print(speaker_embedding_path, self.m.shape)
        self.N_clusters, Emb_dim = self.m.shape

        # Define matrices W (from audio feature) and U (from embedding)
        self.W = nn.Linear(fea_dim, n_heads)
        self.U = nn.Linear(Emb_dim, n_heads)

        self.v = nn.Linear(n_heads, 1)
    
    def forward(self, x, mask):
        '''
        x: Batch * Fea * Time
        mask: Batch * speaker * Time
        '''
        Batch, Fea, Time = x.shape
        num_speaker = mask.shape[1]
        #x_1: [Batch, num_speaker, Time, Fea]
        x_1 = x.repeat(1, num_speaker, 1).reshape(Batch, num_speaker, Fea, Time).transpose(2, 3)

        #x_2: Average [Batch, num_speaker, Fea]
        x_2 = torch.sum(x_1 * mask[..., None], axis=2) / (1e-10 + torch.sum(mask, axis=2)[..., None])

        #self.W(x_2) [Batch, num_speaker, n_heads]
        w = self.W(x_2).repeat(1, self.N_clusters, 1).reshape(Batch, self.N_clusters, num_speaker, self.n_heads).transpose(1, 2)

        #self.U(self.m) [N_clusters, n_heads]
        m = self.m.cuda()
        u = self.U(m).repeat(Batch*num_speaker, 1).reshape(Batch, num_speaker, self.N_clusters, self.n_heads)

        #c: Attention [Batch, num_speaker, N_clusters]
        c = self.v(torch.tanh(w + u)).squeeze(dim=3)

        #a: normalized attention values [Batch, num_speaker, N_clusters]
        a = torch.sigmoid(c)

        #e: weighted sum of the vectors [Batch, num_speaker, Emb_dim]
        #[Batch, num_speaker, N_clusters, 1] * [1, 1, N_clusters, Emb_dim]
        e = torch.sum(a[..., None] * m[None, None, ...], dim=2)

        return e


class FFN(nn.Module):   
    """mlp + residual"""
    def __init__(self, ffn_num_input, ffn_num_hiddens, ffn_num_outputs,
                 **kwargs):
        super(FFN, self).__init__(**kwargs)
        self.linear1 = nn.Linear(ffn_num_input, ffn_num_hiddens)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.1)   #0 or 0.1
        self.linear2 = nn.Linear(ffn_num_hiddens, ffn_num_outputs)

    def forward(self, X):
        return X + self.linear2(self.dropout(self.relu(self.linear1(X))))

class MLP(nn.Module):
    def __init__(self, ffn_num_input, ffn_num_hiddens, ffn_num_outputs,
                 **kwargs):
        super(MLP, self).__init__(**kwargs)
        self.linear1 = nn.Linear(ffn_num_input, ffn_num_hiddens)
        self.layernorm = nn.LayerNorm(ffn_num_hiddens)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(ffn_num_hiddens, ffn_num_outputs)

    def forward(self, X):
        return self.linear2(self.relu(self.layernorm(self.linear1(X))))

                            
def PositionalEmbeddings(num_hiddens, max_len=1000):
        P = torch.zeros((1, max_len, num_hiddens))
        X = torch.arange(max_len, dtype=torch.float32).reshape(
            -1, 1) / torch.pow(10000, torch.arange(
            0, num_hiddens, 2, dtype=torch.float32) / num_hiddens)
        #print(X.shape)
        P[:, :, 0::2] = torch.sin(X)
        P[:, :, 1::2] = torch.cos(X)
        return P

class PositionalEncoding(nn.Module):
    def __init__(self, num_hiddens, dropout, max_len=1000):
        super(PositionalEncoding, self).__init__()
        self.dropout = nn.Dropout(dropout)
        self.P = torch.zeros((1, max_len, num_hiddens))
        X = torch.arange(max_len, dtype=torch.float32).reshape(
            -1, 1) / torch.pow(10000, torch.arange(
            0, num_hiddens, 2, dtype=torch.float32) / num_hiddens)
        self.P[:, :, 0::2] = torch.sin(X)
        self.P[:, :, 1::2] = torch.cos(X)

    def forward(self, X):
        X = X + self.P[:, :X.shape[1], :].to(X.device)
        return self.dropout(X)
           

class DIM_block(nn.Module):
    """DIM_block"""
    def __init__(self,query_size, key_size, num_hiddens, dropout=0.0, **kwargs):
        super(DIM_block, self).__init__(**kwargs)
        self.dropout = nn.Dropout(dropout)
        self.W_q = nn.Linear(query_size, num_hiddens, bias=False)
        self.W_k = nn.Linear(key_size, num_hiddens, bias=False)

    def forward(self, queries, keys_values):

        queries, keys = self.W_q(queries), self.W_k(keys_values)
        d = queries.shape[-1]
        scores = torch.bmm(queries, keys.transpose(1,2)) / math.sqrt(d)
        self.attention_weights = nn.functional.softmax(scores, dim=-1)
        weight_sum = torch.bmm(self.dropout(self.attention_weights), keys_values)
        return weight_sum


class DIM_block2(nn.Module):
    """DIM_block"""
    def __init__(self,query_size, key_size, num_hiddens, dropout=0.0, **kwargs):
        super(DIM_block2, self).__init__(**kwargs)
        self.dropout = nn.Dropout(dropout)
        self.W_q_1 = nn.Linear(query_size, num_hiddens, bias=False)
        self.W_k_1 = nn.Linear(key_size, num_hiddens, bias=False)

        self.W_q_2 = nn.Linear(query_size, num_hiddens, bias=False)
        self.W_k_2 = nn.Linear(key_size, num_hiddens, bias=False)

    def forward(self, queries, keys_values):
        d = queries.shape[-1]

        queries_1, keys_1 = self.W_q_1(queries), self.W_k_1(keys_values)        
        scores_1 = torch.bmm(queries_1, keys_1.transpose(1,2)) / math.sqrt(d)
        self.attention_weights_1 = nn.functional.softmax(scores_1, dim=-1)
        h1 = torch.bmm(self.dropout(self.attention_weights_1), keys_values)

        queries_2, keys_2 = self.W_q_2(queries), self.W_k_2(h1)        
        scores_2 = torch.bmm(queries_2, keys_2.transpose(1,2)) / math.sqrt(d)
        self.attention_weights_2 = nn.functional.softmax(scores_2, dim=-1)
        h2 = torch.bmm(self.dropout(self.attention_weights_2), h1)

        return h2

class MA_MSE_DIM(nn.Module):
    """MA_MSE_DIM"""
    def __init__(self, fea_dim, num_layers=6, speaker_embedding_path="", **kwargs):
        super(MA_MSE_DIM, self).__init__(**kwargs)
        #Dictionary number of cluster * speaker_embedding_dim
        self.m = torch.from_numpy(np.load(speaker_embedding_path).astype(np.float32))
        self.N_clusters, Emb_dim = self.m.shape
        
        self.DIM_blks = nn.Sequential()
        for i in range(num_layers):
            self.DIM_blks.add_module("block"+str(i),
                DIM_block(fea_dim, Emb_dim, Emb_dim))

    def forward(self, X, mask, valid_lens=None, *args):   
        
        Batch, Fea, Time = X.shape
        num_speaker = mask.shape[1]
        x_1 = X.repeat(1, num_speaker, 1).reshape(Batch, num_speaker, Fea, Time).transpose(2, 3) 

        #x_2: Average [Batch, num_speaker, Fea]
        x_2 = torch.sum(x_1 * mask[..., None], axis=2) / (1e-10 + torch.sum(mask, axis=2)[..., None])
        X = x_2  #BND
        m = self.m.cuda()
        kv = m.repeat(Batch, 1).reshape(Batch, self.N_clusters, -1)

        for i, blk in enumerate(self.DIM_blks):
            kv = blk(X, kv)
        return kv # (B, N, D)

class MA_MSE_DIM2(nn.Module):
    """MA_MSE_DIM"""
    def __init__(self, fea_dim, num_layers=6, speaker_embedding_path="", **kwargs):
        super(MA_MSE_DIM2, self).__init__(**kwargs)
        #Dictionary number of cluster * speaker_embedding_dim
        self.m = torch.from_numpy(np.load(speaker_embedding_path).astype(np.float32))
        self.N_clusters, Emb_dim = self.m.shape
        
        self.DIM_blks = nn.Sequential()
        for i in range(int(num_layers)):
            self.DIM_blks.add_module("block"+str(i),
                DIM_block2(fea_dim, Emb_dim, Emb_dim))

    def forward(self, X, mask, valid_lens=None, *args):   
        
        Batch, Fea, Time = X.shape
        num_speaker = mask.shape[1]
        x_1 = X.repeat(1, num_speaker, 1).reshape(Batch, num_speaker, Fea, Time).transpose(2, 3) 

        #x_2: Average [Batch, num_speaker, Fea]
        x_2 = torch.sum(x_1 * mask[..., None], axis=2) / (1e-10 + torch.sum(mask, axis=2)[..., None])
        X = x_2  #BND
        m = self.m.cuda()
        kv = m.repeat(Batch, 1).reshape(Batch, self.N_clusters, -1)

        for i, blk in enumerate(self.DIM_blks):
            kv = blk(X, kv)
        return kv # (B, N, D)
                    
class DecoderBlock(nn.Module):
    def __init__(self, attn_dim ,num_heads, ffn_num_hiddens,
                 mlp_num_input, mlp_num_hiddens, num_outputs, attn_dropout=0., dropout=0., **kwargs):
        super(DecoderBlock, self).__init__(**kwargs)

        self.pos_encoding = PositionalEncoding(num_outputs, dropout)

        #for speaker embeding
        self.num_hiddens = num_outputs
        self.dec_spkemb_weights_1 = nn.Parameter(torch.ones(2) / 2)
        self.dec_spkemb_weights_2 = nn.Parameter(torch.ones(2) / 2)

        self.attn_spkemb_weights = nn.Parameter(torch.ones(2) / 2)


        self.dropout = nn.Dropout(dropout)
        self.mlp = MLP(mlp_num_input, mlp_num_hiddens, num_outputs)
        self.qcontent_proj_1 = nn.Linear(num_outputs, num_outputs)
        self.qpos_proj_1 = nn.Linear(num_outputs, num_outputs) # in DAB-DERT, every component of concat is projed
        self.kcontent_proj_1 = nn.Linear(num_outputs, num_outputs)
        self.kpos_proj_1  = nn.Linear(num_outputs, num_outputs)
        self.v_proj_1 = nn.Linear(num_outputs, num_outputs)
        self.Pre_LN_1_1 = nn.LayerNorm(num_outputs)
        self.Pre_LN_1_2 = nn.LayerNorm(num_outputs)
        self.Pre_LN_1_3 = nn.LayerNorm(num_outputs)
        self.attention1 = MultiheadAttention(attn_dim, num_heads, attn_dropout, vdim=num_outputs)

        
        self.qcontent_proj_2 = nn.Linear(num_outputs, num_outputs)
        self.qpos_proj_2 = nn.Linear(num_outputs, num_outputs)
        self.kcontent_proj_2 = nn.Linear(num_outputs, num_outputs)
        self.v_proj_2 = nn.Linear(num_outputs, num_outputs)   

        self.Pre_LN_2_1 = nn.LayerNorm(num_outputs)
        self.Pre_LN_2_2 = nn.LayerNorm(num_outputs)
        self.Pre_LN_2_3 = nn.LayerNorm(num_outputs)
        self.attention2 = MultiheadAttention(attn_dim, num_heads, attn_dropout, vdim=num_outputs)
        
        self.ffn = FFN(num_outputs, ffn_num_hiddens, num_outputs)
       
                            

    def forward(self, decoder_embeddings, speaker_embeddings, encoder_embeddings):

        speaker_embeddings_ND = self.mlp(speaker_embeddings)
       
        qcontent_1 = self.qcontent_proj_1(decoder_embeddings)
        kcontent_1 = self.kcontent_proj_1(decoder_embeddings)
        q_pos_1 = self.qpos_proj_1(speaker_embeddings_ND)
        k_pos_1 = self.kpos_proj_1(speaker_embeddings_ND)
        
        
        dec_spkemb_norm_weights_1 = nn.functional.softmax(self.dec_spkemb_weights_1, dim=-1)
        dec_spkemb_1 = torch.stack([qcontent_1, q_pos_1], dim=1)
        Query_1 = (dec_spkemb_1 * dec_spkemb_norm_weights_1.view(-1, 1, 1)).sum(dim=1)

    
        dec_spkemb_norm_weights_2 = nn.functional.softmax(self.dec_spkemb_weights_2, dim=-1)
        dec_spkemb_2 = torch.stack([kcontent_1, k_pos_1], dim=1)
        Key_1 = (dec_spkemb_2 * dec_spkemb_norm_weights_2.view(-1, 1, 1)).sum(dim=1)


        Value_1 = self.v_proj_1(decoder_embeddings)

        Value_1 = self.Pre_LN_1_1(Value_1)
        Key_1 = self.Pre_LN_1_2(Key_1)
        Query_1 = self.Pre_LN_1_3(Query_1)   
        
        Query_1, Key_1, Value_1 = Query_1.transpose(0, 1), Key_1.transpose(0, 1), Value_1.transpose(0, 1)
        x_1, _ = self.attention1(Query_1, Key_1, Value_1)  
        x_1 = x_1.transpose(0, 1)
        x_1 = decoder_embeddings + self.dropout(x_1)    
                    
        
        qcontent_2 = self.qcontent_proj_2(x_1)
        kcontent_2 = self.kcontent_proj_2(encoder_embeddings)
        q_pos_2 = self.qpos_proj_2(speaker_embeddings_ND)
        
        attn_spkemb_norm_weights = nn.functional.softmax(self.attn_spkemb_weights, dim=-1)
        attn_spkemb = torch.stack([qcontent_2, q_pos_2], dim=1)
        Query_2 = (attn_spkemb * attn_spkemb_norm_weights.view(-1, 1, 1)).sum(dim=1)
        
        
        Key_2 = self.pos_encoding(kcontent_2 * math.sqrt(self.num_hiddens))

        
        Value_2 = self.v_proj_2(encoder_embeddings)
        Value_2 = self.Pre_LN_2_1(Value_2)
        Key_2 = self.Pre_LN_2_2(Key_2)
        Query_2 = self.Pre_LN_2_3(Query_2)
        Query_2, Key_2, Value_2 = Query_2.transpose(0, 1), Key_2.transpose(0, 1), Value_2.transpose(0, 1)                         
        x_3, _ = self.attention2(Query_2, Key_2, Value_2)  
        x_3 = x_3.transpose(0, 1)
        x_3 = x_1 + self.dropout(x_3)         
        out = self.ffn(x_3)
        
        return out


class Decoder(nn.Module):                           
    def __init__(self, attn_dim ,num_heads, ffn_num_hiddens,
        mlp_num_input, mlp_num_hiddens, num_outputs, num_layers, attn_dropout=0., dropout=0., decode_Time=800, **kwargs):
        super(Decoder, self).__init__(**kwargs)
        self.blks = nn.Sequential()
        for i in range(num_layers):
            self.blks.add_module("block_"+str(i),
                DecoderBlock(attn_dim ,num_heads, ffn_num_hiddens,
                mlp_num_input, mlp_num_hiddens, num_outputs, attn_dropout, dropout))
        self.output_layer = nn.Linear(num_outputs,  decode_Time)
        
    def forward(self, decoder_embeddings, speaker_embeddings, encoder_embeddings):
        for blk in self.blks:
            decoder_embeddings = blk(decoder_embeddings, speaker_embeddings, encoder_embeddings)
        out = self.output_layer(decoder_embeddings)
        return out


class Decoder_MOE_Block_from_config(nn.Module):
    def __init__(self, attn_dim ,num_heads, num_slots, num_experts,
                 mlp_num_input, mlp_num_hiddens, num_outputs, moe_geglu=True, attn_dropout=0., dropout=0., num_spk=4, **kwargs):
        super(Decoder_MOE_Block_from_config, self).__init__(**kwargs)

        self.pos_encoding = PositionalEncoding(num_outputs, dropout)

        #for speaker embeding
        self.num_hiddens = num_outputs
        self.dec_spkemb_weights_1 = nn.Parameter(torch.ones(2) / 2)
        self.dec_spkemb_weights_2 = nn.Parameter(torch.ones(2) / 2)

        self.attn_spkemb_weights = nn.Parameter(torch.ones(2) / 2)


        self.dropout = nn.Dropout(dropout)
        self.mlp = MLP(mlp_num_input, mlp_num_hiddens, num_outputs)
        self.qcontent_proj_1 = nn.Linear(num_outputs, num_outputs)
        self.qpos_proj_1 = nn.Linear(num_outputs, num_outputs) # in DAB-DERT, every component of concat is projed
        self.kcontent_proj_1 = nn.Linear(num_outputs, num_outputs)
        self.kpos_proj_1  = nn.Linear(num_outputs, num_outputs)
        self.v_proj_1 = nn.Linear(num_outputs, num_outputs)
        self.Pre_LN_1_1 = nn.LayerNorm(num_outputs)
        self.Pre_LN_1_2 = nn.LayerNorm(num_outputs)
        self.Pre_LN_1_3 = nn.LayerNorm(num_outputs)
        self.attention1 = MultiheadAttention(attn_dim, num_heads, attn_dropout, vdim=num_outputs)

        
        self.qcontent_proj_2 = nn.Linear(num_outputs, num_outputs)
        self.qpos_proj_2 = nn.Linear(num_outputs, num_outputs)
        self.kcontent_proj_2 = nn.Linear(num_outputs, num_outputs)
        self.v_proj_2 = nn.Linear(num_outputs, num_outputs)   

        self.Pre_LN_2_1 = nn.LayerNorm(num_outputs)
        self.Pre_LN_2_2 = nn.LayerNorm(num_outputs)
        self.Pre_LN_2_3 = nn.LayerNorm(num_outputs)
        self.attention2 = MultiheadAttention(attn_dim, num_heads, attn_dropout, vdim=num_outputs)

        self.moe = SS_MoE(dim = num_outputs, num_experts = num_experts, num_slots=num_slots, geglu = moe_geglu, seq_len = num_spk)

                            

    def forward(self, decoder_embeddings, speaker_embeddings, encoder_embeddings):

        speaker_embeddings_ND = self.mlp(speaker_embeddings)
       
        qcontent_1 = self.qcontent_proj_1(decoder_embeddings)
        kcontent_1 = self.kcontent_proj_1(decoder_embeddings)
        q_pos_1 = self.qpos_proj_1(speaker_embeddings_ND)
        k_pos_1 = self.kpos_proj_1(speaker_embeddings_ND)
        
        
        dec_spkemb_norm_weights_1 = nn.functional.softmax(self.dec_spkemb_weights_1, dim=-1)
        dec_spkemb_1 = torch.stack([qcontent_1, q_pos_1], dim=1)
        Query_1 = (dec_spkemb_1 * dec_spkemb_norm_weights_1.view(-1, 1, 1)).sum(dim=1)

    
        dec_spkemb_norm_weights_2 = nn.functional.softmax(self.dec_spkemb_weights_2, dim=-1)
        dec_spkemb_2 = torch.stack([kcontent_1, k_pos_1], dim=1)
        Key_1 = (dec_spkemb_2 * dec_spkemb_norm_weights_2.view(-1, 1, 1)).sum(dim=1)


        Value_1 = self.v_proj_1(decoder_embeddings)

        Value_1 = self.Pre_LN_1_1(Value_1)
        Key_1 = self.Pre_LN_1_2(Key_1)
        Query_1 = self.Pre_LN_1_3(Query_1)   
        
        Query_1, Key_1, Value_1 = Query_1.transpose(0, 1), Key_1.transpose(0, 1), Value_1.transpose(0, 1)
        x_1, _ = self.attention1(Query_1, Key_1, Value_1)  
        x_1 = x_1.transpose(0, 1)
        x_1 = decoder_embeddings + self.dropout(x_1)    
                    
        
        qcontent_2 = self.qcontent_proj_2(x_1)
        kcontent_2 = self.kcontent_proj_2(encoder_embeddings)
        q_pos_2 = self.qpos_proj_2(speaker_embeddings_ND)
        
        attn_spkemb_norm_weights = nn.functional.softmax(self.attn_spkemb_weights, dim=-1)
        attn_spkemb = torch.stack([qcontent_2, q_pos_2], dim=1)
        Query_2 = (attn_spkemb * attn_spkemb_norm_weights.view(-1, 1, 1)).sum(dim=1)
        
        
        Key_2 = self.pos_encoding(kcontent_2 * math.sqrt(self.num_hiddens))

        
        Value_2 = self.v_proj_2(encoder_embeddings)
        Value_2 = self.Pre_LN_2_1(Value_2)
        Key_2 = self.Pre_LN_2_2(Key_2)
        Query_2 = self.Pre_LN_2_3(Query_2)
        Query_2, Key_2, Value_2 = Query_2.transpose(0, 1), Key_2.transpose(0, 1), Value_2.transpose(0, 1)                         
        x_3, _ = self.attention2(Query_2, Key_2, Value_2)  
        x_3 = x_3.transpose(0, 1)
        x_3 = x_1 + self.dropout(x_3)
        out = x_3 + self.moe(x_3)

        return out


class Decoder_MOE_from_config(nn.Module):                           
    def __init__(self, attn_dim ,num_heads, num_slots, num_experts,
        mlp_num_input, mlp_num_hiddens, num_outputs, num_layers, moe_geglu=True, moe_layer=[0,1,2,3,4,5], ffn_num_hiddens=1024, attn_dropout=0., dropout=0., decode_Time=800, num_spk=4, **kwargs):
        super(Decoder_MOE_from_config, self).__init__(**kwargs)
        self.blks = nn.Sequential()
        for i in range(num_layers):
            if i in moe_layer:
                self.blks.add_module("block_moe_"+str(i),
                    Decoder_MOE_Block_from_config(attn_dim ,num_heads, num_slots, num_experts,
                    mlp_num_input, mlp_num_hiddens, num_outputs, moe_geglu, attn_dropout, dropout, num_spk))
            else:
                self.blks.add_module("block_"+str(i),
                    DecoderBlock(attn_dim ,num_heads, ffn_num_hiddens,
                    mlp_num_input, mlp_num_hiddens, num_outputs, attn_dropout, dropout))

        self.output_layer = nn.Linear(num_outputs,  decode_Time)
        
    def forward(self, decoder_embeddings, speaker_embeddings, encoder_embeddings):
        for blk in self.blks:
            decoder_embeddings = blk(decoder_embeddings, speaker_embeddings, encoder_embeddings)
        out = self.output_layer(decoder_embeddings)
        return out


class MULTI_MAM_SE_S2S_MOE_model_learnable_IO_moe_from_config(nn.Module):
    '''
    speaker embedding + mse
    INPUT (MFCC)
    IDCT: MFCC to FBANK
    Batchnorm
    Stats pooling: batchnorm-cmn
    Combine inputs:  (batchnorm, batchnorm-cmn Speaker Detection Block
    4 layers CNN: Conv2d (in channels, out channels, kernel size, stride=1, padding=0 dilation=1, groups=1, bias=True, padding mode=zeros) 1 layer Splice-embedding:  (Convld SD, ivector-k) Linear layer
    2 layers Shared-blstm
    Attention
    1 layers CNN: Convld (in channels, out channels, kernel size, stride=1, padding=0 dilation=1, groups=1, bias=True, padding mode=zeros) Attention layer
    1 layers Combine-speaker
    1 layers BLSTM
    1 layers Dense: 4 dependent FC layers
    '''
    def __init__(self, configs):
        super(MULTI_MAM_SE_S2S_MOE_model_learnable_IO_moe_from_config, self).__init__()
        self.configs = configs
        print(configs)
        self.cnn_configs = configs["cnn_configs"]
        self.output_speaker = configs["output_speaker"]
        self.dropout = nn.Dropout(configs["decoder_dropout"])
        self.batchnorm = nn.BatchNorm2d(1)
        self.average_pooling = nn.AvgPool1d(configs["average_pooling"], stride=1, padding=configs["average_pooling"]//2)
        self.down_sampling = nn.Conv1d(in_channels=128*20,out_channels=configs["fea_dim"],kernel_size=1)
        
        self.conformer = Conformer(dim=configs["fea_dim"], depth=configs["conformer_layers"], conv_kernel_size=configs["conformer_conv_kernel_size"], ff_dropout=configs["conformer_ff_dropout"])        
       
        # MA-MSE
        self.mamse1 = MA_MSE_DIM2(fea_dim=configs["fea_dim"], num_layers=configs["ma_mse_layers_1"], speaker_embedding_path=configs["embedding_path1"])
        self.mamse2 = MA_MSE_DIM2(fea_dim=configs["fea_dim"], num_layers=configs["ma_mse_layers_2"], speaker_embedding_path=configs["embedding_path2"])

        # Speaker Detection Block
        self.Conv2d_SD = nn.Sequential()
        self.Conv2d_SD.add_module('CNN2D_BN_Relu_SD1', CNN2D_BN_Relu(self.cnn_configs[0][0], self.cnn_configs[0][1], self.cnn_configs[0][2], self.cnn_configs[0][3]))
        self.Conv2d_SD.add_module('CNN2D_BN_Relu_SD2', CNN2D_BN_Relu(self.cnn_configs[1][0], self.cnn_configs[1][1], self.cnn_configs[1][2], self.cnn_configs[1][3]))
        self.Conv2d_SD.add_module('CNN2D_BN_Relu_SD3', CNN2D_BN_Relu(self.cnn_configs[2][0], self.cnn_configs[2][1], self.cnn_configs[2][2], self.cnn_configs[2][3]))
        self.Conv2d_SD.add_module('CNN2D_BN_Relu_SD4', CNN2D_BN_Relu(self.cnn_configs[3][0], self.cnn_configs[3][1], self.cnn_configs[3][2], self.cnn_configs[3][3]))
        
        #Decoder
        #self.decoder = Decoder_MOE_learnable_IO(attn_dim=configs["fea_dim"] ,num_heads=configs["decoder_num_heads"], num_experts=configs["num_experts"],mlp_num_input=100+100+256, mlp_num_hiddens=configs["decoder_mlp_num_hiddens"], num_outputs=configs["fea_dim"], num_layers=configs["decoder_layers"], attn_dropout=configs["decoder_attn_dropout"], dropout=configs["decoder_dropout"], decode_Time=configs["decode_Time"])
        self.decoder = Decoder_MOE_from_config(attn_dim=configs["fea_dim"] ,num_heads=configs["decoder_num_heads"], num_slots=configs["num_slots"], num_experts=configs["num_experts"], moe_geglu=configs["moe_geglu"], ffn_num_hiddens=configs["decoder_ffn_num_hiddens"], moe_layer=configs["moe_layer"], mlp_num_input=100+100+256, mlp_num_hiddens=configs["decoder_mlp_num_hiddens"], num_outputs=configs["fea_dim"], num_layers=configs["decoder_layers"], attn_dropout=configs["decoder_attn_dropout"], dropout=configs["decoder_dropout"], decode_Time=configs["decode_Time"], num_spk=configs["output_speaker"])
        
       
    def forward(self, x, overall_embedding, mask, **kwargs):
        '''
        x: Batch * Freq * Time
        mask : Batch * speaker * Time
        Batch * speaker(4) * Embedding
        nframe: descend order
        '''
        batchsize, Freq, Time = x.shape

        x_3 = self.batchnorm(x.reshape(batchsize, 1, Freq, Time)).squeeze(dim=1) 

        x_3_mean = self.average_pooling(x_3) #(B, dim, T) (8, 40, T)

        x_4 = torch.cat((x_3, x_3_mean), dim=1).reshape(batchsize, 2, Freq, Time)

        x_5 = self.Conv2d_SD(x_4)
        x_6 = self.down_sampling(x_5.reshape(batchsize, -1, Time)) 
        Freq = x_6.shape[1]
        embedding1 = self.mamse1(x_6, mask) # [Batch, num_speaker, Emb_dim_1]     (8, 4, 100)
        embedding2 = self.mamse2(x_6, mask) # [Batch, num_speaker, Emb_dim_2]     (8, 4, 256)

        final_embedding = torch.cat((embedding1, embedding2, overall_embedding), dim=2) 
        x_6_BTD = x_6.transpose(1, 2)    # (B, T, D)
        positional_embeddings = PositionalEmbeddings(self.configs["fea_dim"], max_len=1000).cuda()
        x_6_pos = x_6_BTD + positional_embeddings[:, :x_6_BTD.shape[1], :] 
        x_7 = self.conformer(x_6_pos)  
        decoder_embeddings = torch.zeros((x_7.shape[0], self.output_speaker, self.configs["fea_dim"])).cuda()
        out = self.decoder(decoder_embeddings, final_embedding, x_7)
        return out


if __name__=='__main__':
    # from config import configs3_4Speakers_ivector_ivector128_xvectors128_S2S_MA_MSE_DIM as config_train
    from config import configs3_4Speakers_ivector_ivector128_xvectors128_S2S_MA_MSE_DIM_MOE as config_train
    # from config import configs3_8Speakers_ivector_ivector128_xvectors128_S2S_MA_MSE_DIM_WAVLM as config_train
    # from config import configs3_8Speakers_ivector_ivector128_xvectors128_S2S_MA_MSE_DIM_WHISPER as config_train
    # path="/train33/sppro/permanent/gbyang/code/NSD-MS2S/local_gb/run_model/model_d_528"
    #path="/train33/sppro/permanent/gbyang/code/NSD-MS2S/local_gb/run_model/model_cc_530"

    # print('load from ', path)
    # ckpt_path = "/train33/sppro/permanent/gbyang/code/NSD-MS2S/local_gb/run_model/model_d_528"
    # dicts = torch.load(path, map_location='cpu')
    # model_ckpt = { k.replace("out_logit_transform2", "out_logit_transform"): v for k, v in dicts['model'].items()}
    # dicts["model"] = model_ckpt
    # torch.save(dicts, "/train33/sppro/permanent/gbyang/code/NSD-MS2S/local_gb/run/model_cc")
    # cpkt = dicts["model"]
    # configs = dicts["configs"]
    # net = MULTI_MAM_SE_S2S_MOE_model_learnable_IO_moe_from_config(configs).cuda()
    net = MULTI_MAM_SE_S2S_MOE_model_learnable_IO_moe_from_config(config_train).cuda()
    # import time

    B = 10

    mel = torch.randn(B, 40, 800).cuda()  # 
    overall_embedding = torch.randn(B, 4, 100).cuda()
    mask = torch.randint(0, 2, size=(B, 4, 800), dtype=torch.int).cuda()

    out = net(mel, overall_embedding, mask)
    print(out.shape)  # (B, T, D)
    # config_train['moe_layer'] = [3,4,5]
    # config_train['num_experts'] = 4
    # config_train['num_slots'] = 4
    # config_train['moe_geglu'] = True
    # net = MULTI_MAM_SE_S2S_MOE_model_learnable_IO_moe_from_config(config_train).cuda()
    # net.load_state_dict(cpkt)

